FROM adoptopenjdk:8-jdk-openj9-bionic as final

LABEL maintainer="Jordan Cartwright @ IBM <jordan.cartwright@ibm.com>"

COPY ./script.sh /script.sh
RUN ["chmod", "+x", "/script.sh"]

ENTRYPOINT ["/script.sh"]